# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tpom < Formula
  desc "A minimalist pomodoro timer for the terminal"
  homepage "https://github.com/MaximusBenjamin/terminal-pomodoro"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MaximusBenjamin/terminal-pomodoro/releases/download/v0.4.0/tpom_0.4.0_darwin_amd64.tar.gz"
      sha256 "dc9419915ba64de6dc15a344f3c7823bea834d03989407d8b7740d1c36d430c0"

      define_method(:install) do
        bin.install "tpom"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MaximusBenjamin/terminal-pomodoro/releases/download/v0.4.0/tpom_0.4.0_darwin_arm64.tar.gz"
      sha256 "fdf6e966d133dfd70b2a25309dd1f7ce8e5e9e6ab83be2c5882c67ab790d727f"

      define_method(:install) do
        bin.install "tpom"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/MaximusBenjamin/terminal-pomodoro/releases/download/v0.4.0/tpom_0.4.0_linux_amd64.tar.gz"
      sha256 "45b16e44e4970d234920f6f2cdc4539ab5a4092018e4e8f874e8cb60ffb50a59"
      define_method(:install) do
        bin.install "tpom"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MaximusBenjamin/terminal-pomodoro/releases/download/v0.4.0/tpom_0.4.0_linux_arm64.tar.gz"
      sha256 "4701ca4b3f6105c42bd59277af5bdad489f36ef2a5545d14e839720f98835c2c"
      define_method(:install) do
        bin.install "tpom"
      end
    end
  end
end
