# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tpom < Formula
  desc "A minimalist pomodoro timer for the terminal"
  homepage "https://github.com/MaximusBenjamin/terminal-pomodoro"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MaximusBenjamin/terminal-pomodoro/releases/download/v0.5.0/tpom_0.5.0_darwin_amd64.tar.gz"
      sha256 "40deeb917012afec896364adc9fcb0a2b7723323c4ebd624116d84fc0c9eac88"

      define_method(:install) do
        bin.install "tpom"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MaximusBenjamin/terminal-pomodoro/releases/download/v0.5.0/tpom_0.5.0_darwin_arm64.tar.gz"
      sha256 "0e24c4d9472ba90e20302bb57162c6598c250b84838a6e72d83c57e2d710c250"

      define_method(:install) do
        bin.install "tpom"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/MaximusBenjamin/terminal-pomodoro/releases/download/v0.5.0/tpom_0.5.0_linux_amd64.tar.gz"
      sha256 "5bb17c036b3ebd0e3e062c44ada546eda185480cbe217348484c73e675a82e0f"
      define_method(:install) do
        bin.install "tpom"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MaximusBenjamin/terminal-pomodoro/releases/download/v0.5.0/tpom_0.5.0_linux_arm64.tar.gz"
      sha256 "35b658bf346749a948221536d8f21889275ad502aa303dadc613c34186540908"
      define_method(:install) do
        bin.install "tpom"
      end
    end
  end
end
